name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: windows-latest
    #runs-on: ubuntu-24.04
    #runs-on: macos-latest
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Ensure reports directory exists
        run: mkdir -p cypress/reports  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
            browser: chrome      

      - name: Install JUnit Viewer
        run: npm install -g junit-viewer

      - name: Convert JUnit XML to HTML
        run: junit-viewer --results=cypress/reports --save=cypress/reports/report.html

      - name: Display HTML report
        run: cat cypress/reports/report.html      