name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Ensure reports directory exists
        run: mkdir -p cypress/reports  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
            
      - name: List Mochawesome reports
        run: dir cypress\reports

      - name: Display HTML report in logs
        run: type cypress\reports\mochawesome.html      

      #- name: Install JUnit Viewer
      #  run: npm install -g junit-viewer

      #- name: Convert JUnit XML to HTML
      #  run: junit-viewer --results=cypress/reports --save=cypress/reports/report.html

      #- name: Display HTML report
      #  run: cat cypress/reports/report.html      