name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Ensure reports directory exists
        run: mkdir -p cypress/reports  

      - name: Run Cypress tests with Dashboard
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
            record: true
            key: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Display Cypress Dashboard link
        run: echo "Check the Cypress Dashboard for detailed test results."    