name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Ensure reports directory exists
        run: mkdir -p cypress/reports  

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: chrome